### ISSUE TITLE
executing a java code with compilation error is giving failed to start Gauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-java#63] opened 2016-07-15 04:04 UTC
**Expected behavior**
Should give compilation error and not other errors

**Actual behavior**
Fails to start gauge api
```
src/test/java/StepImplementation.java:10: error: variable arg1 is already defined in method implementation1
    public void implementation1(Object arg1, Object arg1) {
                                                    ^
1 error
process /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/javac with pid 2596 quit unexpectedly. exit status 1
Failed to start gauge API: Timed out connecting to [::]:51524
```
**Steps to replicate**
1. Create a spec
```
gauge --init java
```
2. Create a spec
```
with Simple Params
===============

Scenario Heading
----------------
* Say "Gauge" to "Gauge"
```
2. Create the implementation
```
@Step("Say <Gauge> to <Gauge>")
    public void implementation1(Object arg1, Object arg1) {
    }
```
3. run the specs
And it gives the above error

**Version**
```
Gauge version: 0.5.1.nightly-2016-07-13

Plugins
-------
html-report (2.1.1.nightly-2016-07-13)
java (0.4.2.nightly-2016-07-07)
```

**Comment by mahendrakariya** [comment] 2016-10-12 10:00
Duplicate of https://github.com/getgauge/gauge/issues/516.

**Closed by mahendrakariya** 2016-10-12 10:00 UTC
Labels: bug, duplicate
