### ISSUE TITLE
Should fetch implementations from dependencies.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-java#236] opened 2019-02-04 05:51 UTC
**Expected Behaviour**
Create step implementations in a java project. Compile the jar and add it as a library in `libs` folder of a Gauge project.
Now implement the step in a scenario in the Gauge project. 
The step implementation should be considered from the compiled jar. 
While editing, the step should be shown as implemented.

**Actual Behaviour**
Create step implementations in a java project. Compile the jar and add it as a library in `libs` folder of a Gauge project.
Now implement the step in a scenario in the Gauge project. 
The step implementation is not found.
While editing, the step is not shown as implemented.

*Note: This used to work in gauge java versions < 0.7.0.*

**Comment by haroon-sheikh** [comment] 2019-02-11 10:22
@nehashri Is this related to https://github.com/getgauge/gauge-java/issues/234 and should now be fixed in 0.7.1

**Comment by nehashri** [comment] 2019-02-11 11:43
@haroon-sheikh no this is not related to #234. This issue as explained, occurs only during editing (writing specs in VSCode or other lsp clients) and has nothing to do with execution.

**Comment by ajoecker** [comment] 2019-02-22 06:01
not sure if this is related - but using a Java Maven project, one is able to have the step implementation in a dependency lib and this is picked up and used correctly during implemenation and execution (this is for gauge java version 0.6.9 & 0.7.1)

**Comment by alpha1592** [comment] 2020-03-03 20:54
I was using Gauge-Java v0.7.2 and was able to find @Steps defined in Maven Dependencies (Jars).
I recently upgraded to Gauge-Java v0.7.4, Gauge v1.0.7 and html-report v4.0.9 and now unable to find implementations. The IntelliJ plugin does not show red lines, which means its detecting that an implementation is there. However, The implementations are not picked up at runtime. 

Can you provide some update on this?

Error:
```
Skipped: Common: Wait for ten seconds.
Filename: specs\ExampleFeature.spec
Message: Step implementation not found
```

```
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.9)
java (0.7.4)
json-report (0.3.2)
screenshot (0.0.1)
spectacle (0.1.4)
```

**Comment by alpha1592** [comment] 2020-03-17 17:57
I have confirmed this issue. Here are the details.
From what i can gather, the Step Validation occurs before the scanning of the Test Steps. The scanning actually does pick up the steps in the Jars, but the verification, because it happens before throws and error and tells the user to implement the steps..

Below are the snippet of importance (IMO) and you can see from the timestamp, that the validation occurs before the scanning. I have also verified this using the debugger in IntelliJ. 

I am also attaching two Java-Maven-Spring projects that demonstrate this issue. While i am using spring in my case, i don't think its related to this issue. 

**gauge-spring-lib:** The library JAR file that has some predefined Test Steps
 * In the pom.xml for this project, you can set the Gauge-Java Version by setting the property.
`<gauge.version>0.7.4</gauge.version>`

**gauge-spring-test:** The test project using the library JAR as a dependency. Using maven for dependency management.

you can run the `Build.bat` to build both projects and run the test or use `Run.bat` to just build and run the test project using maven. 

** Test Step Validation**
`com.thoughtworks.gauge.processor.ValidateStepProcessor.java`

```
17-03-2020 13:15:33.068 [Gauge] [DEBUG] Validation started.
17-03-2020 13:15:33.240 [Gauge] [ERROR] [ValidationError] C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec:10 Step implementation not found => 'Step A: This is in a Jar file...'
17-03-2020 13:15:33.240 [Gauge] [ERROR] [ValidationError] C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec:11 Step implementation not found => 'Step B: This is in a Jar file...'
```

**Test Step Scanning**
`com.thoughtworks.gauge.scan.StepsScanner.java`

```
17-03-2020 13:15:35.596 [java] [DEBUG] Scanning packages for steps
17-03-2020 13:15:35.614 [java] [DEBUG] Scanning packages for hooks
17-03-2020 13:15:36.024 [java] [DEBUG] Using com.example.spring.RegisterSpring as class initializer
```

## Sample Project
[Issue-236 Sample Project](https://github.com/getgauge/gauge-java/files/4344958/Issue-236.zip)

## LOGS

### **Gauge v1.0.6 / Gauge-Java v0.7.2 / html-report v4.0.8**
```
17-03-2020 13:01:24.978 [Gauge] [DEBUG] Plugin java is already installed.
17-03-2020 13:01:24.983 [Gauge] [DEBUG] Plugin html-report is already installed.
17-03-2020 13:01:25.747 [Gauge] [DEBUG] Checking updates...
17-03-2020 13:01:25.762 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:01:26.264 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:01:26.458 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:01:29.249 [Gauge] [DEBUG] Api Request Received: messageType:GetStepValueRequest messageId:4 stepValueRequest:<stepText:"Step B: This is in a Jar file..." > 
17-03-2020 13:01:29.250 [Gauge] [DEBUG] Sending API response: messageType:GetStepValueResponse messageId:4 stepValueResponse:<stepValue:<stepValue:"Step B: This is in a Jar file..." parameterizedStepValue:"Step B: This is in a Jar file..." > > 
17-03-2020 13:01:29.259 [Gauge] [DEBUG] Api Request Received: messageType:GetStepValueRequest messageId:4 stepValueRequest:<stepText:"Step A: This is in a Jar file..." > 
17-03-2020 13:01:29.259 [Gauge] [DEBUG] Sending API response: messageType:GetStepValueResponse messageId:4 stepValueResponse:<stepValue:<stepValue:"Step A: This is in a Jar file..." parameterizedStepValue:"Step A: This is in a Jar file..." > > 
17-03-2020 13:01:29.260 [Gauge] [DEBUG] Api Request Received: messageType:GetStepValueRequest messageId:4 stepValueRequest:<stepText:"This is a local Step" > 
17-03-2020 13:01:29.260 [Gauge] [DEBUG] Sending API response: messageType:GetStepValueResponse messageId:4 stepValueResponse:<stepValue:<stepValue:"This is a local Step" parameterizedStepValue:"This is a local Step" > > 
17-03-2020 13:01:30.957 [Gauge] [INFO] Closing connection [127.0.0.1:58414] cause: EOF
17-03-2020 13:01:30.969 [Gauge] [DEBUG] Plugin [Html Report] with pid [20328] has exited
17-03-2020 13:01:30.996 [Gauge] [INFO] Closing connection [127.0.0.1:58406] cause: read tcp 127.0.0.1:58383->127.0.0.1:58406: wsarecv: An existing connection was forcibly closed by the remote host.
17-03-2020 13:01:31.069 [Gauge] [INFO] Specifications:	1 executed	1 passed	0 failed	0 skipped
17-03-2020 13:01:31.069 [Gauge] [INFO] Scenarios:	2 executed	2 passed	0 failed	0 skipped
17-03-2020 13:01:31.069 [Gauge] [INFO] 
Total time taken: 144ms
```

### **Gauge v1.0.6 / Gauge-Java v0.7.3 / html-report v4.0.8**
```
17-03-2020 13:07:38.402 [Gauge] [DEBUG] Plugin java is already installed.
17-03-2020 13:07:38.407 [Gauge] [DEBUG] Plugin html-report is already installed.
17-03-2020 13:07:39.217 [Gauge] [DEBUG] Checking updates...
17-03-2020 13:07:39.228 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:07:39.559 [java] [DEBUG] Connecting to port: 58798
17-03-2020 13:07:39.583 [java] [DEBUG] Connected to 127.0.0.1:58798
17-03-2020 13:07:39.752 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:07:39.950 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:07:42.691 [java] [DEBUG] Scanning packages for steps
17-03-2020 13:07:42.707 [java] [DEBUG] Scanning packages for hooks
17-03-2020 13:07:43.053 [java] [DEBUG] Using com.example.spring.RegisterSpring as class initializer
17-03-2020 13:07:44.557 [Gauge] [INFO] Closing connection [127.0.0.1:58817] cause: EOF
17-03-2020 13:07:44.572 [Gauge] [DEBUG] Plugin [Html Report] with pid [19580] has exited
17-03-2020 13:07:44.573 [java] [DEBUG] Kill process request recieved
17-03-2020 13:07:44.672 [Gauge] [INFO] Specifications:	1 executed	1 passed	0 failed	0 skipped
17-03-2020 13:07:44.672 [Gauge] [INFO] Scenarios:	2 executed	2 passed	0 failed	0 skipped
17-03-2020 13:07:44.672 [Gauge] [INFO] 
Total time taken: 148ms
17-03-2020 13:07:44.678 [Gauge] [INFO] Updates are available. Run `gauge update -c` for more info.
```

### **Gauge v1.0.7 / Gauge-Java v0.7.4 / html-report v4.0.9**

**api.log**
_you can see that the steps in the Jars are picked up..._
```
17-03-2020 13:14:22.582 [Gauge] [INFO] Watching directory: C:\dev\gauge\issues\gauge-spring-test\specs
17-03-2020 13:14:22.590 [Gauge] [DEBUG] Found 1 files
17-03-2020 13:14:22.591 [Gauge] [INFO] Initializing concepts cache with 0 concepts
17-03-2020 13:14:22.593 [Gauge] [INFO] Initializing specs cache with 1 specs
17-03-2020 13:14:22.593 [Gauge] [DEBUG] Adding specs from C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec
17-03-2020 13:14:22.593 [Gauge] [INFO] Initializing steps cache with 1 steps
17-03-2020 13:14:22.593 [Gauge] [INFO] Gauge daemon initialized and listening on port: 59279
17-03-2020 13:15:09.229 [Gauge] [DEBUG] Api Request Received: messageType:GetStepValueRequest messageId:4 stepValueRequest:<stepText:"This is a local Step" > 
17-03-2020 13:15:09.230 [Gauge] [DEBUG] Sending API response: messageType:GetStepValueResponse messageId:4 stepValueResponse:<stepValue:<stepValue:"This is a local Step" parameterizedStepValue:"This is a local Step" > > 
17-03-2020 13:15:09.811 [Gauge] [DEBUG] Api Request Received: messageType:GetStepValueRequest messageId:4 stepValueRequest:<stepText:"Step A: This is in a Jar file..." > 
17-03-2020 13:15:09.811 [Gauge] [DEBUG] Sending API response: messageType:GetStepValueResponse messageId:4 stepValueResponse:<stepValue:<stepValue:"Step A: This is in a Jar file..." parameterizedStepValue:"Step A: This is in a Jar file..." > > 
17-03-2020 13:15:09.812 [Gauge] [DEBUG] Api Request Received: messageType:GetStepValueRequest messageId:4 stepValueRequest:<stepText:"Step B: This is in a Jar file..." > 
17-03-2020 13:15:09.812 [Gauge] [DEBUG] Sending API response: messageType:GetStepValueResponse messageId:4 stepValueResponse:<stepValue:<stepValue:"Step B: This is in a Jar file..." parameterizedStepValue:"Step B: This is in a Jar file..." > > 
```

**gauge.log**
```
17-03-2020 13:15:25.778 [Gauge] [DEBUG] Created gauge_screenshots_dir at C:\dev\gauge\issues\gauge-spring-test\.gauge\screenshots
17-03-2020 13:15:25.800 [Gauge] [DEBUG] Plugin java is already installed.
17-03-2020 13:15:25.803 [Gauge] [DEBUG] Plugin html-report is already installed.
17-03-2020 13:15:25.806 [Gauge] [DEBUG] Parsing started.
17-03-2020 13:15:25.806 [Gauge] [DEBUG] Started concepts parsing.
17-03-2020 13:15:25.840 [Gauge] [DEBUG] 0 concepts parsing completed.
17-03-2020 13:15:25.841 [Gauge] [DEBUG] Started specifications parsing.
17-03-2020 13:15:25.843 [Gauge] [DEBUG] 1 specifications parsing completed.
17-03-2020 13:15:25.844 [Gauge] [DEBUG] Parsing completed.
17-03-2020 13:15:26.720 [Gauge] [DEBUG] Checking updates...
17-03-2020 13:15:26.733 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/html-report?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:15:28.021 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/java?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:15:28.215 [Gauge] [DEBUG] Downloading https://downloads.gauge.org/plugin/screenshot?l=java&p=html-report,java,screenshot&o=windows&a=amd64
17-03-2020 13:15:32.861 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 59410
17-03-2020 13:15:33.068 [Gauge] [DEBUG] Successfully made the connection with runner with port: 59410
17-03-2020 13:15:33.068 [Gauge] [DEBUG] Validation started.
17-03-2020 13:15:33.240 [Gauge] [ERROR] [ValidationError] C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec:10 Step implementation not found => 'Step A: This is in a Jar file...'
17-03-2020 13:15:33.240 [Gauge] [ERROR] [ValidationError] C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec:11 Step implementation not found => 'Step B: This is in a Jar file...'
17-03-2020 13:15:33.242 [Gauge] [DEBUG] Run started
17-03-2020 13:15:33.247 [Gauge] [DEBUG] Starting Html Report plugin
17-03-2020 13:15:33.399 [Gauge] [DEBUG] Attempting to connect to grpc server at port: 59415
17-03-2020 13:15:33.401 [Gauge] [DEBUG] Successfully made the connection with plugin with port: 59415
17-03-2020 13:15:33.402 [Gauge] [DEBUG] Initialising suite data store.
17-03-2020 13:15:35.596 [java] [DEBUG] Scanning packages for steps
17-03-2020 13:15:35.614 [java] [DEBUG] Scanning packages for hooks
17-03-2020 13:15:36.024 [java] [DEBUG] Using com.example.spring.RegisterSpring as class initializer
17-03-2020 13:15:37.325 [html-report] [DEBUG] Transformed SuiteResult to report structure
17-03-2020 13:15:37.831 [html-report] [INFO] Successfully generated html-report to => C:\dev\gauge\issues\gauge-spring-test\reports\html-report\index.html
17-03-2020 13:15:37.831 [Gauge] [DEBUG] Sending kill message to Html Report plugin.
17-03-2020 13:15:37.831 [html-report] [DEBUG] Done generating HTML report using theme from C:\Tools\Gauge-1.0.7\plugins\html-report\4.0.9\themes\default
17-03-2020 13:15:38.340 [Gauge] [DEBUG] Runner with PID:2704 has exited
17-03-2020 13:15:38.340 [Gauge] [INFO] Specifications:	1 executed	1 passed	0 failed	0 skipped
17-03-2020 13:15:38.340 [Gauge] [INFO] Scenarios:	1 executed	1 passed	0 failed	1 skipped
17-03-2020 13:15:38.340 [Gauge] [INFO] 
Total time taken: 4.069s
```

**Test Execution log**
```
Testing started at 1:15 PM ...
C:\Tools\Gauge-1.0.7\bin\gauge.exe run --machine-readable --hide-suggestion --simple-console C:/dev/gauge/issues/gauge-spring-test/specs/Example.spec

[ValidationError] C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec:10 Step implementation not found => 'Step A: This is in a Jar file...'
[ValidationError] C:\dev\gauge\issues\gauge-spring-test\specs\Example.spec:11 Step implementation not found => 'Step B: This is in a Jar file...'

[DEBUG] Spring loaded Class: ExampleSteps
[INFO] This is a Local Step in this project...

Skipped: Step A: This is in a Jar file...
Filename: specs\Example.spec
Message: Step implementation not found


Skipped: Step B: This is in a Jar file...
Filename: specs\Example.spec
Message: Step implementation not found

Successfully generated html-report to => C:\dev\gauge\issues\gauge-spring-test\reports\html-report\index.html

Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	1 skipped

Total time taken: 4.069s

Process finished with exit code 0
```

Hope this clears up this issue.

**Comment by alpha1592** [comment] 2020-03-25 13:11
Hi, 
Any idea when this issue will be resolved / next release will be? I am heavily affected by the HTML-report plugin defect related to proto-message and would love to upgrade to try and resolve that issue. But I cannot as this will be a show stopper for my team.

**Comment by sriv** [comment] 2020-03-25 13:26
hi @alpha1592 - we fixed this issue for gauge-dotnet recently, and we will pick this up soon. Unfortunately, we don't have any timelines at this point.

**Comment by alpha1592** [comment] 2020-03-25 14:29
Thanks, I appreciate it.

**Comment by olejkavn** [comment] 2020-04-06 14:04
@sriv  do you have any updates about gauge-java?

**Comment by Dmitriy85** [comment] 2020-04-08 08:32
@sriv any approximate dates? This issue is blocking us from move a huge api test solution to new version of gauge. Please provide any info.

**Comment by sriv** [comment] 2020-04-08 08:48
@alpha1592 @olejkavn @Dmitriy85  - I've picked this up, will post updates once I make progress.

**Comment by sriv** [comment] 2020-04-09 13:11
Update - I have changes that enables executing a project with steps defined in an external dependency.

The challenge is to get gauge-vscode to detect this dependency and not mark them as unimplemented.

**Comment by Dmitriy85** [comment] 2020-04-22 07:37
Hi @sriv. Do you have any blockers regarding the merge of the PR? Any approximate dates for the release with this changes? Thanks in advance!

**Comment by sriv** [comment] 2020-04-22 08:37
hi @Dmitriy85 - need to do some testing. We'll try to make a release by next week.

**Closed** 2020-04-24 04:36 UTC
Labels: bug, triage
