### ISSUE TITLE
Scenario Datastore not getting the correct values when run in parallel

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/gauge-java#468] opened 2020-06-29 11:14 UTC
### Expected behavior
Each scenario uses its own thread for accessing the datastore.

### Actual behavior
Scenario Datastore not getting the correct values when run in parallel and enable_multithreading is set to true.

### Steps to reproduce
1. Create 2 specs with a scenario each
2. Both scenarios to save an item to datastore using the same key
3. Assert in scenarios to validate the key for each scenario.

### Gauge version
```
Gauge version: 1.1.1
Plugins
-------
flash (0.0.2)
html-report (4.0.11)
java (0.7.9)
json-report (0.3.3)
reportportal (1.7.0)
reportserver (0.2.0)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)
```

**Comment by haroon-sheikh** [comment] 2020-06-29 11:21
Maybe related to #455

**Comment by haroon-sheikh** [comment] 2020-07-05 18:18
@sriv After a bit investigation, it looks like this problem is when you're using dynamic parameters as a table. And for each row, scenario writes to scenario datastore using the same key, its not always getting the correct response back depending on the row of dynamic table.

**Comment by haroon-sheikh** [comment] 2020-07-08 07:56
Think the issue is happening since https://github.com/getgauge/gauge-java/pull/433

**Comment by sriv** [comment] 2020-07-08 08:10
thanks for digging up @haroon-sheikh - #433 had to be done because otherwise the footprint of gauge-java was way too high.

What is the behaviour if you checkout 697d487523d3d56642d32382d8cdfaca09cd9685 and install gauge-java from source?

**Comment by haroon-sheikh** [comment] 2020-07-13 13:44
@sriv I've validated that 697d487 and 0.7.7 is working fine. As soon as we upgrade to 0.7.8, we start seeing the issues with datastore.

**Comment by sriv** [comment] 2020-07-21 13:07
@haroon-sheikh gauge-java 0.7.9 [is out](https://github.com/getgauge/gauge-java/releases/tag/v0.7.9) and has some changes/improvements.

Please check if this issue persists in this version. I could not see this issue on a gauge-java-maven project using `0.7.9`

**Comment by haroon-sheikh** [comment] 2020-07-22 19:18
@sriv Just tested this with 0.7.9 and unfortunately this is still an issue when there's dynamic parameters as a table on top of the spec.

**Comment by sriv** [comment] 2020-07-23 02:53
could you do one more test please:

run `mvn dependency:purge-local-repository` in your project (this would clear the m2 cache for your project's dependency and restore it). I ask this to ensure that there is no residue from our tests earlier which built gauge-java 0.7.9 from source, but does not have all the changes.

also `gauge uninstall java --version 0.7.9 && gauge install java`

**Comment by haroon-sheikh** [comment] 2020-07-23 08:21
> could you do one more test please:
> 
> run `mvn dependency:purge-local-repository` in your project (this would clear the m2 cache for your project's dependency and restore it). I ask this to ensure that there is no residue from our tests earlier which built gauge-java 0.7.9 from source, but does not have all the changes.
> 
> also `gauge uninstall java --version 0.7.9 && gauge install java`

Still getting the same issue after purging the repository.

**Comment by sriv** [comment] 2020-07-24 17:02
@haroon-sheikh - I could not replicate it with table driven scenario. I've uploaded the project I used to test here: https://github.com/sriv/gauge-java-468

Please, could you look at this and see if I'm missing something? Feel free to modify and send a pull request.

**Comment by sriv** [comment] 2020-07-31 07:43
@haroon-sheikh would you be able to test `fix-scenariodatastore` branch and see if there is an improvement?

**Comment by haroon-sheikh** [comment] 2020-07-31 16:32
@sriv The issues looks to have fixed some of the errors in accessing datastore but not all.

Also seeing this when running in parallel:

```sh
panic: runtime error: index out of range [2] with length 2

goroutine 639 [running]:
github.com/getgauge/gauge/execution.(*stepExecutor).executeStep(0xc000b4ec30, 0xc000b47200, 0xc000735b30, 0x0)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/stepExecutor.go:32 +0x9ff
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeStep(0xc000c129a0, 0xc000b47200, 0xc000a649a0, 0xc000ed9160, 0xc000130000)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/scenarioExecutor.go:165 +0x174
github.com/getgauge/gauge/execution.(*scenarioExecutor).executeSteps(0xc000c129a0, 0xc000c7e900, 0xf, 0x10, 0xc0013e3e00, 0xf, 0x14, 0xc000ed9160)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/scenarioExecutor.go:143 +0xa6
github.com/getgauge/gauge/execution.(*scenarioExecutor).execute(0xc000c129a0, 0x1844da0, 0xc00074a580, 0x185b900, 0xc000ed9160)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/scenarioExecutor.go:75 +0x94e
github.com/getgauge/gauge/execution.(*specExecutor).executeScenario(0xc000f5b740, 0xc00074a580, 0xc000d4e7f0, 0x1514803, 0x2)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/specExecutor.go:312 +0x265
github.com/getgauge/gauge/execution.(*specExecutor).executeScenarios(0xc000f5b740, 0xc000d4e7f0, 0x2, 0x2, 0x2, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/specExecutor.go:270 +0x83
github.com/getgauge/gauge/execution.(*specExecutor).executeTableRelatedScenarios(0xc000f5b740, 0xc000d4e7f0, 0x2, 0x2, 0x0, 0x0)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/specExecutor.go:137 +0x82
github.com/getgauge/gauge/execution.(*specExecutor).executeSpec(0xc000f5b740, 0xc0015994a0, 0xc0006a7dc0)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/specExecutor.go:157 +0x190
github.com/getgauge/gauge/execution.(*specExecutor).execute(0xc000f5b740, 0x1010101, 0xc00013aaa0)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/specExecutor.go:118 +0x929
github.com/getgauge/gauge/execution.(*simpleExecution).executeSpecs(0xc000b7a460, 0xc0004e9e90, 0xc000203420, 0x0, 0x0)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/simpleExecution.go:123 +0x193
github.com/getgauge/gauge/execution.(*simpleExecution).execute(0xc000b7a460)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/simpleExecution.go:84 +0x10c
github.com/getgauge/gauge/execution.(*parallelExecution).startSpecsExecutionWithRunner(0xc0016c2000, 0xc0004e9e90, 0x185ba80, 0xc00013aaa0, 0x7)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/parallelExecution.go:256 +0xa3
github.com/getgauge/gauge/execution.(*parallelExecution).executeLazily.func1(0xc0016c2000, 0x7)
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/parallelExecution.go:169 +0x8f
created by github.com/getgauge/gauge/execution.(*parallelExecution).executeLazily
        /private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/parallelExecution.go:167 +0xc6
```

**Comment by cyberjaime45** [comment] 2020-08-06 01:46
In my case I had similar issues, sometimes  thread 6 was getting values from thread 1. Sometimes null exceptions.  I had to make sure my code is thread safe and the static method  that saves and retrieves  data is synchronized. After all these changes, it worked just fine.

**Comment by zabil** [comment] 2020-08-06 09:56
Gauge's design of DataStore access may have caused this

https://github.com/getgauge/gauge-java/blob/2c341fb54320e6bd7b6297d41f765af544a66e36/src/main/java/com/thoughtworks/gauge/datastore/DataStoreFactory.java#L15-L26

The `DataStore` is Threadsafe, however it's usage

```
// Adding value
DataStore scenarioStore = DataStoreFactory.getScenarioDataStore();
scenarioStore.put("element-id", "455678");
// Fetching Value
String elementId = (String) scenarioStore.get("element-id");
```


Opens `scenarioStore` to thread safety issues as instance can be be scoped unsafely.

The intention was to use it as 

```
DataStoreFactory.getScenarioDataStore().put("element-id", "455678")
DataStoreFactory.getScenarioDataStore().get("element-id", "455678")
```

I propose deprecating `DataStoreFactory` in favour of `SpecDataStore`, `SuiteDataStore`, `ScenarioDataStore` so that Datastore instance is not exposed it will also make accessing the `DataStore` much easier and thread safe by design for example

```
// Adding value
ScenarioDataStore.put("element-id", "455678");
// Fetching Value
String elementId = (String) ScenarioDataStore.get("element-id");
```

**Comment by haroon-sheikh** [comment] 2020-08-06 10:10
Thanks @zabil - I have changed all of the DataStore access to use this `DataStoreFactory.getScenarioDataStore().put()` approach but the issue still persists. 

I wonder if your suggestion along with changes from Sriv https://github.com/getgauge/gauge-java/pull/481 will resolve this.

**Comment by zabil** [comment] 2020-09-14 11:15
@haroon-sheikh did you get a chance to revisit this issue? The new release of gauge java plugin 0.7.10 is also out.

**Comment by haroon-sheikh** [comment] 2020-09-14 12:20
Thanks @zabil - I'll give it a go as soon as it's available in the repository to download and install. Will keep you updated.

**Comment by BugDiver** [comment] 2020-09-25 09:15
Closing this as required PRs have been merged and released. Feel free to reopen if the issue still occurs.

**Closed by BugDiver** 2020-09-25 09:15 UTC
Labels: bug
