### ISSUE TITLE
All the failed tests are reported in a successful state in the HTML report with Appium

### ISSUE THREAD

**Issue by zbrea** [getgauge/gauge-java#617] opened 2021-07-12 17:20 UTC
### Expected behavior
In the tests which cannot find elements (id) on the screen of the app, must have passed in error in the logs and in the html reporting.

### Actual behavior
all tests are successfully passed., even if they cannot find elements (id) on the screen of the app, since I started using gauge-java, for Appium for a native application.

### Steps to reproduce
When I run my tests which must fail, I have the impression that the html-report extension does not manage the drivers on Appium.
You will find the details of the logs here. I deleted the personal info in the logs)

### Gauge version
❯ gauge -v
Gauge version: 1.3.2
Commit Hash: 063444f

Plugins
-------
flash (0.0.2)
html-report (4.1.0)
java (0.7.15)
json-report (0.3.6)
screenshot (0.0.1)
spectacle (0.1.4)
xml-report (0.2.3)

Log :
---------------------------------------------
Running tool: mvn.cmd -q clean compile test-compile gauge:execute -Dflags=--hide-suggestion,--simple-console -DspecsDir=specs\Saisie.spec

juil. 12, 2021 5:57:06 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
A_Saisie_1
  ## Login
This element 'username' is found.

This element 'Id_Invalide_password' is not found  : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-...................................
*** Element info: {Using=id, value=Id_Invalide_password}

Exception occured while clickin link Id_Invalid_Submit_Button : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-40.......................................
*** Element info: {Using=id, value=Id_Invalid_Submit_Button}

The elment 'fragment_home_client_text' is not display : org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.id: fragment_home_client_text (tried for 10 second(s) with 500 milliseconds interval)

   |colis      |
   |-----------|
   |14112014026|
  Retrait en saisie

Exception occured while clickin link tab_button_left : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de1.......................................
*** Element info: {Using=id, value=tab_button_left}

Exception occured while clickin link btn_input : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de.............................
*** Element info: {Using=id, value=btn_input}

This element 'edt_reference' is not found  : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-40c1-9a1f-f64f547........
*** Element info: {Using=id, value=edt_reference}

Exception occured while clickin link btn_validate_reference : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-4..........................
*** Element info: {Using=id, value=btn_validate_reference}

Exception occured while clickin link txv_ok : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-..........................
*** Element info: {Using=id, value=txv_ok}

Exception occured while clickin link txv_next_step : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-..........................
*** Element info: {Using=id, value=txv_next_step}

Exception occured while clickin link signature_pad : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-..........................
*** Element info: {Using=id, value=signature_pad}

Exception occured while clickin link txv_next_step : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-..........................
*** Element info: {Using=id, value=txv_next_step}

Exception occured while clickin link txv_next_step : org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 2dfbc1fd-de15-..........................
Element info: {Using=id, value=txv_next_step}

Successfully generated html-report to => c:\Workspace\POC-Lab\POC3\reports\html-report\index.html

Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped
----

Total time taken: 49.096s
Updates are available. Run `gauge update -c` for more info.

**Comment by sriv** [comment] 2021-07-13 03:38
Duplicate of https://github.com/getgauge/html-report/issues/277. Closing.

**Closed by sriv** 2021-07-13 03:38 UTC
