### ISSUE TITLE
Custom screenshot grabber throws cryptic message

### ISSUE THREAD

**Issue by ryudice** [getgauge/gauge-java#253] opened 2019-03-04 14:16 UTC
### Expected behavior
The screenshot should be taken using the custom screenshot grabber, and the custom screenshot grabber should be called

### Actual behavior
I get the folowing message:

```Failed to take Custom screenshot: SelenideScreenshotGrabber : null```

The method is not even called because the message is not output to stdout.

### Steps to reproduce
1. Add this custom screenshot grabber
```java
public class SelenideScreenshotGrabber implements ICustomScreenshotGrabber {

    @Override
    public byte[] takeScreenshot() {
        System.out.print("Grabbing screenshot with Selenide");
        TakesScreenshot driver = ((TakesScreenshot) WebDriverRunner.getWebDriver());
        return driver.getScreenshotAs(OutputType.BYTES);

        
    }
}
```

2. Run the tests on selenium grid

### Gauge version
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.6)
java (0.7.1)
screenshot (0.0.1)
spectacle (0.1.3)
****
```

**Comment by nehashri** [comment] 2019-03-06 10:48
duplicate of #254.

**Closed by nehashri** 2019-03-06 10:48 UTC
Labels: community
