### ISSUE TITLE
Support for java 10

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/gauge-java#175] opened 2018-08-06 06:16 UTC
### Expected behavior
Should be able to run the specification without any errors/warnings.

### Actual behavior
Get the fallowing warnings
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/apoorvag/.gauge/plugins/java/0.6.8/libs/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
### Steps to reproduce
1. Install Java 10
2. init gauge java template using `gauge init java`
3. run `gauge run secs`

### Gauge version
```
Gauge version: 1.0.1
Commit Hash: 8281d03

Plugins
-------
java (0.6.8)
screenshot (0.0.1)
html-report (4.0.5)
```

**Comment by nehashri** [comment] 2018-08-06 08:29
Duplicate of https://github.com/getgauge/gauge-java/issues/149

**Closed by nehashri** 2018-08-06 08:29 UTC
Labels: ready
