### ISSUE TITLE
Unable to use gauge-java with gauge gradle plugin: "Gauge or Java runner is not installed!"

### ISSUE THREAD

**Issue by ed0906** [getgauge/gauge-java#367] opened 2020-02-12 16:37 UTC
### Expected behavior
When running `./gradlew clean build gauge` our gauge tests should run

### Actual behavior
```
./gradlew clean build gauge
> Task :clean
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :assemble
> Task :compileTestKotlin
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
> Task :check
> Task :build
> Task :gauge FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gauge'.
> Gauge or Java runner is not installed! Read http://getgauge.io/documentation/user/current/getting_started/download_and_install.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

```

### Steps to reproduce
1. `brew install gauge`
2. `gauge install java`
3. `./gradlew clean build gauge`

##### build.gradle.kts
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

object Versions {
    const val gauge = "1.8.0"
    const val gaugeJava = "0.7.3"
}

plugins {
    kotlin("jvm") version "1.3.40"
    id("java")
    id("org.gauge") version "1.8.0"
}

group = "tests"
version = ""

repositories {
    mavenCentral()
}

dependencies {
    // Kotlin
    testImplementation("org.jetbrains.kotlin:kotlin-reflect")
    testImplementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Gauge
    testImplementation("com.thoughtworks.gauge:gauge-java:${Versions.gaugeJava}")
}

tasks {
    withType<KotlinCompile> {
        kotlinOptions {
            freeCompilerArgs = listOf("-Xjsr305=strict")
            jvmTarget = "12"
        }
    }

    wrapper {
        version = "6.1.1"
    }
}
```

### Gauge version
```
Gauge version: 1.0.6

Plugins
-------
java (0.7.3)

```

### Gradle version
```
------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          12.0.2 (AdoptOpenJDK 12.0.2+10)
OS:           Mac OS X 10.15.3 x86_64

```

**Comment by sriv** [comment] 2020-02-14 11:04
I created a sample yesterday - https://github.com/sriv/gauge-gradle-demo/

I saw the error you mention on windows, but that was because of my install script not adding the location of gauge in `PATH`. Once I set that, it started working.

You can see the run logs here: https://github.com/sriv/gauge-gradle-demo/actions/runs/39235968

Note that I am using gauge `1.0.7` and gauge-java `0.7.4`

**Comment by negiDharmendra** [comment] 2020-02-17 10:26
Duplicate of getgauge/gauge-gradle-plugin#43

**Closed by negiDharmendra** 2020-02-17 10:26 UTC
